# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62d538698420cc3798fb000311ecc4b7df70f4dc18c55d15d2cb4fe21e63a962e0c5ba7a0b8d60d7054894b55c7c2079f5bd45150c6e7c0b7caa6c7cfa7e33fb

test:
  secret_key_base: 8126c9123522f82f1ee730a362f38418a82462a9f8b0c299218c6229f0c9b6b372ae129aac72d1269bff253855bd6dd43987dfb0c5114c25f835f9f61aa3a5be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
